mybatis:
  type-aliases-package: pe.edu.upc.RsReport.mappers
spring:
  profiles:
    active: dev

---

spring:
  profiles: test
name: test-YAML
environment: test
datasource:
  jndi-name: jdbc/SmartDB
auth-security:
  token:
    secretCode: "SecretKeyToGenJWTs"
    expirationTime: 100_000
    tokenPrefix: "Bearer "
    requestString: "Authorization"
banner: banner.txt

---

spring:
  profiles: dev
name: dev-YAML
environment: dev
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://mysql36516-test-server1.jl.serv.net.mx/dbappfinance?useSSL=false
  username: user_smart
  password: admin
  maximumPoolSize: 5
auth-security:
  token:
    secretCode: "SecretKeyToGenJWTs"
    expirationTime: 100_000
    tokenPrefix: "Bearer "
    requestString: "Authorization"
server:
  port: 8083
  servlet:
    context-path: /
banner: banner.txt